### ISSUE TITLE
Generate binary builds (via Goreleaser)

### ISSUE THREAD

**Issue by Sean-Der** [proemergotech/chrome-webrtc-packet-log-parser#3]
Hey @pongraczgabor87 

I am happy to do the work on this, but it would be really helpful we had binary builds! It is really easy to do with [goreleaser](https://github.com/goreleaser/goreleaser) then people don't even have to have Golang installed locally.

I also posted this on [Twitter](https://twitter.com/_pion/status/1263944976913674241) and it was quite popular, congrats :)

**Comment by Sean-Der** [comment]
This is the one I did for [pion/turn](https://github.com/pion/turn/blob/master/.goreleaser.yml) I can port it to work here, but since I don't have write access you will have to generate the binaries yourself.

**Comment by pongraczgabor87** [comment]
I'm happy to create the binary for you, but at the moment this project is not "perfect".      
We only want to share it. Everybody could pimp it up to his/her needs (special format, additional packet parsing, etc...).

**Comment by pongraczgabor87** [comment]
@Sean-Der I created a GoReleaser setup with GitHub actions, so when somebody pushes a tag/create a release it will create binaries. :)
